version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd architectures/blue-green-deployment/lambda
      - npm ci
  pre_build:
    commands:
      - npm test
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - pwd
      - docker build -t $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag  $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION $IMAGE_REPO_URL:latest
      - docker push $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $IMAGE_REPO_URL:latest

  post_build:
    commands:
      - CURRENT_VERSION=$(aws lambda get-alias --function-name "$APP_LAMBDA_NAME" --name live --query 'FunctionVersion' --output text)

      # update function to new image and publish a new version
      - aws lambda update-function-code --function-name "$APP_LAMBDA_NAME" --image-uri "$IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION" >/dev/null
      - aws lambda wait function-updated --function-name "$APP_LAMBDA_NAME"
      - TARGET_VERSION=$(aws lambda publish-version --function-name "$APP_LAMBDA_NAME" --query 'Version' --output text)

      # create appspec.yml for CodeDeploy
      - |
        cat > appspec.yml <<EOF
        version: 0.0
        Resources:
          - myLambdaFunction:
              Type: AWS::Lambda::Function
              Properties:
                Name: "$APP_LAMBDA_NAME"
                Alias: "live"
                CurrentVersion: "$CURRENT_VERSION"
                TargetVersion: "$TARGET_VERSION"
        EOF

artifacts:
  files:
    - "**/*"
