version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd architectures/blue-green-deployment/lambda
      - npm ci
  pre_build:
    commands:
      - npm test
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - pwd
      - docker build -t $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag  $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION $IMAGE_REPO_URL:latest
      - docker push $IMAGE_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $IMAGE_REPO_URL:latest

artifacts:
  files:
    - "**/*"
